# Generated by Django 3.0.8 on 2020-10-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201005_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
